-- V7: 微信支付支持
ALTER TABLE activities ADD COLUMN IF NOT EXISTS fee INTEGER DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS paid BOOLEAN DEFAULT false;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS amount INTEGER DEFAULT 0;
ALTER TABLE submissions ADD COLUMN IF NOT EXISTS wx_transaction_id VARCHAR(64);
